<a href="https://colab.research.google.com/github/aliabdelmonam/Used-Car-Price-for-Regression/blob/main/Regreesion_for_used_car_price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import copy
from sklearn.preprocessing import StandardScaler,OrdinalEncoder,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
tr= pd.read_csv('/content/drive/MyDrive/DataSet/regression for used car price train.csv')
ts= pd.read_csv('/content/drive/MyDrive/DataSet/regression for used car price test.csv')
y_zz = pd.read_csv('/content/drive/MyDrive/DataSet/Regression cars for sample case.csv')

In [ ]:
tr.shape

(188533, 13)

In [ ]:
tr.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [ ]:
tr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB

In [ ]:
df_train = copy.deepcopy(tr)
df_test = copy.deepcopy(ts)

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
print(df_train['engine'].iloc[:150].to_string())

0           172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel
1           252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel
2      320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...
3           420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel
4           208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
5           252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
6          333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel
7      355.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...
8                        2.7L V6 24V PDI DOHC Twin Turbo
9      425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...
10         312.0HP 3.6L V6 Cylinder Engine Gasoline Fuel
11                   Electric Motor Electric Fuel System
12          420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel
13         333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel
14          523.0HP 4.4L 8 Cylinder Engine Gasoline Fuel
15          503.0HP 4.0L 8 Cylinder Engine Gasoline Fuel
16          420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel
17     395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...
18          310.0HP 4.6L 8 Cylinder Engine Gasoline Fuel
19          469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel
20                                 5.2L V10 40V PDI DOHC
21          429.0HP 5.0L 8 Cylinder Engine Gasoline Fuel
22         210.0HP 3.7L V6 Cylinder Engine Gasoline Fuel
23     335.0HP 3.0L V6 Cylinder Engine Gasoline/Mild ...
24          316.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
25          381.0HP 5.7L 8 Cylinder Engine Gasoline Fuel
26            450.0HP 6.7L 8 Cylinder Engine Diesel Fuel
27          420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel
28         236.0HP 4.0L V6 Cylinder Engine Gasoline Fuel
29          211.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
30          220.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
31          255.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
32           518.0HP Electric Motor Electric Fuel System
33         268.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
34         174.0HP 2.8L V6 Cylinder Engine Gasoline Fuel
35          240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
36          248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
37          563.0HP 5.5L 8 Cylinder Engine Gasoline Fuel
38          241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
39                                  3.6L V6 24V GDI DOHC
40     230.0HP 3.0L Straight 6 Cylinder Engine Gasoli...
41            450.0HP 6.7L 8 Cylinder Engine Diesel Fuel
42          430.0HP 6.2L 8 Cylinder Engine Gasoline Fuel
43                       4.0L V8 32V GDI DOHC Twin Turbo
44           835.0HP Electric Motor Electric Fuel System
45                                  5.7L V8 16V MPFI OHV
46          300.0HP 5.4L 8 Cylinder Engine Gasoline Fuel
47     425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...
48         310.0HP 6.8L 10 Cylinder Engine Gasoline Fuel
49          280.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
50         295.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
51                                 Dual Motor - Standard
52           518.0HP Electric Motor Electric Fuel System
53         348.0HP 3.8L V6 Cylinder Engine Gasoline Fuel
54          560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel
55         285.0HP 3.6L V6 Cylinder Engine Gasoline Fuel
56          241.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
57          252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel
58          300.0HP 4.4L 8 Cylinder Engine Gasoline Fuel
59          302.0HP 5.0L 8 Cylinder Engine Gasoline Fuel
60                       3.0L V6 24V GDI DOHC Twin Turbo
61         300.0HP 3.6L V6 Cylinder Engine Gasoline Fuel
62          490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel
63          300.0HP 5.3L 8 Cylinder Engine Gasoline Fuel
64          560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel
65          490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel
66          200.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
67          416.0HP 4.0L 8 Cylinder Engine Gasoline Fuel
68          179.0HP 2.5L 4 Cylinder Engine Gasoline Fuel
69         302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
70                      3.8L V8 32V MPFI DOHC Twin Turbo
71         295.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
72                3.4L V6 24V PDI DOHC Twin Turbo Hybrid
73     385.0HP 6.2L 8 Cylinder Engine Flex Fuel Capab...
74          160.0HP 2.4L 4 Cylinder Engine Gasoline Fuel
75     385.0HP 3.8L Flat 6 Cylinder Engine Gasoline Fuel
76         210.0HP 3.3L V6 Cylinder Engine Gasoline Fuel
77          385.0HP 5.0L 8 Cylinder Engine Gasoline Fuel
78         270.0HP 4.0L V6 Cylinder Engine Gasoline Fuel
79     425.0HP 3.0L Straight 6 Cylinder Engine Gasoli...
80          560.0HP 4.0L 8 Cylinder Engine Gasoline Fuel
81          160.0HP 2.4L 4 Cylinder Engine Gasoline Fuel
82          248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
83         210.0HP 4.0L V6 Cylinder Engine Gasoline Fuel
84                       3.5L V6 24V PDI DOHC Twin Turbo
85          310.0HP 2.3L 4 Cylinder Engine Gasoline Fuel
86         302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
87     350.0HP 6.7L Straight 6 Cylinder Engine Diesel...
88     190.0HP 4.0L Straight 6 Cylinder Engine Gasoli...
89          350.0HP 2.3L 4 Cylinder Engine Gasoline Fuel
90          181.0HP 1.6L 4 Cylinder Engine Gasoline Fuel
91                            2.0L I4 16V PDI DOHC Turbo
92          300.0HP 4.6L 8 Cylinder Engine Gasoline Fuel
93         270.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
94          248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
95         265.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
96          345.0HP 5.7L 8 Cylinder Engine Gasoline Fuel
97         400.0HP 3.0L V6 Cylinder Engine Gasoline Fuel
98         261.0HP 4.0L V6 Cylinder Engine Gasoline Fuel
99          355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel
100    335.0HP 3.0L V6 Cylinder Engine Gasoline/Mild ...
101         536.0HP 5.5L 8 Cylinder Engine Gasoline Fuel
102         320.0HP 5.3L 8 Cylinder Engine Gasoline Fuel
103         503.0HP 4.0L 8 Cylinder Engine Gasoline Fuel
104    333.0HP 3.2L Straight 6 Cylinder Engine Gasoli...
105         402.0HP 4.7L 8 Cylinder Engine Gasoline Fuel
106         450.0HP 4.0L 8 Cylinder Engine Gasoline Fuel
107    382.0HP 3.0L Straight 6 Cylinder Engine Gasoli...
108         180.0HP 1.8L 4 Cylinder Engine Gasoline Fuel
109         420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel
110         617.0HP 4.4L 8 Cylinder Engine Gasoline Fuel
111                                 2.4L I4 16V GDI DOHC
112         355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel
113        310.0HP 6.8L 10 Cylinder Engine Gasoline Fuel
114         240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
115        173.0HP 2.7L V6 Cylinder Engine Gasoline Fuel
116    389.0HP 3.0L Straight 6 Cylinder Engine Plug-I...
117         208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
118         429.0HP 4.7L 8 Cylinder Engine Gasoline Fuel
119    385.0HP 6.2L 8 Cylinder Engine Flex Fuel Capab...
120        210.0HP 3.7L V6 Cylinder Engine Gasoline Fuel
121        318.0HP 3.6L V6 Cylinder Engine Gasoline Fuel
122                                 2.0 Liter DOHC Turbo
123                                3.6L V6 24V MPFI DOHC
124        325.0HP 3.7L V6 Cylinder Engine Gasoline Fuel
125        365.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
126                                3.6L V6 24V MPFI DOHC
127         340.0HP 5.7L 8 Cylinder Engine Gasoline Fuel
128    235.0HP 3.2L Straight 6 Cylinder Engine Gasoli...
129        302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
130        255.0HP 3.6L V6 Cylinder Engine Gasoline Fuel
131        270.0HP 3.5L V6 Cylinder Engine Gasoline Fuel
132    169.0HP 2.5L 4 Cylinder Engine Flex Fuel Capab...
133                   6.0L V8 16V MPFI OHV Flexible Fuel
134                                3.6L V6 24V MPFI DOHC
135        210.0HP 3.7L V6 Cylinder Engine Gasoline Fuel
136         173.0HP 2.4L 4 Cylinder Engine Gasoline Fuel
137    385.0HP 6.2L 8 Cylinder Engine Flex Fuel Capab...
138         248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
139         710.0HP 4.0L 8 Cylinder Engine Gasoline Fuel
140         211.0HP 2.0L 4 Cylinder Engine Gasoline Fuel
141        225.0HP 3.3L V6 Cylinder Engine Gasoline Fuel
142    400.0HP 3.8L Flat 6 Cylinder Engine Gasoline Fuel
143         270.0HP 2.3L 4 Cylinder Engine Gasoline Fuel
144                           2.0L I4 16V GDI DOHC Turbo
145                      3.0L V6 24V GDI DOHC Twin Turbo
146    350.0HP 3.4L Flat 6 Cylinder Engine Gasoline Fuel
147                           2.3L I4 16V GDI DOHC Turbo
148         366.0HP 6.0L 8 Cylinder Engine Gasoline Fuel
149        400.0HP 3.0L V6 Cylinder Engine Gasoline Fuel

In [ ]:
for col in df_train.select_dtypes(include='object'):
    print(col)
    print(df_train[col].nunique())
    print(df_train[col].unique())
    print('-----------------------------------------')

brand
57
['MINI' 'Lincoln' 'Chevrolet' 'Genesis' 'Mercedes-Benz' 'Audi' 'Ford'
 'BMW' 'Tesla' 'Cadillac' 'Land' 'GMC' 'Toyota' 'Hyundai' 'Volvo'
 'Volkswagen' 'Buick' 'Rivian' 'RAM' 'Hummer' 'Alfa' 'INFINITI' 'Jeep'
 'Porsche' 'McLaren' 'Honda' 'Lexus' 'Dodge' 'Nissan' 'Jaguar' 'Acura'
 'Kia' 'Mitsubishi' 'Rolls-Royce' 'Maserati' 'Pontiac' 'Saturn' 'Bentley'
 'Mazda' 'Subaru' 'Ferrari' 'Aston' 'Lamborghini' 'Chrysler' 'Lucid'
 'Lotus' 'Scion' 'smart' 'Karma' 'Plymouth' 'Suzuki' 'FIAT' 'Saab'
 'Bugatti' 'Mercury' 'Polestar' 'Maybach']
-----------------------------------------
model
1897
['Cooper S Base' 'LS V8' 'Silverado 2500 LT' ... 'e-Golf SE'
 'Integra w/A-Spec Tech Package' 'IONIQ Plug-In Hybrid SEL']
-----------------------------------------
fuel_type
7
['Gasoline' 'E85 Flex Fuel' nan 'Hybrid' 'Diesel' 'Plug-In Hybrid' '–'
 'not supported']
-----------------------------------------
engine
1117
['172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel'
 '252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel'
 '320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capability' ...
 '78.0HP 1.2L 3 Cylinder Engine Gasoline Fuel'
 '139.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas'
 '313.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas']
-----------------------------------------
transmission
52
['A/T' 'Transmission w/Dual Shift Mode' '7-Speed A/T' '8-Speed A/T'
 '10-Speed Automatic' '1-Speed A/T' '6-Speed A/T' '10-Speed A/T'
 '9-Speed A/T' '8-Speed Automatic' '9-Speed Automatic' '5-Speed A/T'
 'Automatic' '7-Speed Automatic with Auto-Shift' 'CVT Transmission'
 '5-Speed M/T' 'M/T' '6-Speed M/T' '6-Speed Automatic' '4-Speed Automatic'
 '7-Speed M/T' '2-Speed A/T' '1-Speed Automatic' 'Automatic CVT'
 '4-Speed A/T' '6-Speed Manual' 'Transmission Overdrive Switch'
 '8-Speed Automatic with Auto-Shift' '7-Speed Manual' '7-Speed Automatic'
 '9-Speed Automatic with Auto-Shift' '6-Speed Automatic with Auto-Shift'
 '6-Speed Electronically Controlled Automatic with O' 'F' 'CVT-F'
 '8-Speed Manual' 'Manual' '–' '2' '6 Speed At/Mt' '5-Speed Automatic'
 '2-Speed Automatic' '8-SPEED A/T' '7-Speed' 'Variable'
 'Single-Speed Fixed Gear' '8-SPEED AT'
 '10-Speed Automatic with Overdrive' '7-Speed DCT Automatic'
 'SCHEDULED FOR OR IN PRODUCTION' '6-Speed' '6 Speed Mt']
-----------------------------------------
ext_col
319
['Yellow' 'Silver' 'Blue' 'Black' 'White' 'Snowflake White Pearl Metallic'
 'Gray' 'Green' 'Santorini Black Metallic' 'Purple'
 'Ebony Twilight Metallic' 'Red' 'Magnetite Black Metallic'
 'Diamond Black' 'Vega Blue' 'Beige' 'Gold' 'Platinum White Pearl'
 'Metallic' 'White Frost Tri-Coat' 'Firecracker Red Clearcoat'
 'Phytonic Blue Metallic' 'Blu' 'Orange' 'Brown'
 'Brilliant Silver Metallic' 'Black Raven' 'Black Clearcoat' 'Firenze Red'
 'Agate Black Metallic' 'Glacial White Pearl' 'Majestic Plum Metallic'
 'designo Diamond White Metallic' 'Oxford White' 'Black Sapphire Metallic'
 'Mythos Black' 'Granite Crystal Clearcoat Metallic'
 'White Diamond Tri-Coat' 'Magnetite Gray Metallic'
 'Carpathian Grey Premium Metallic' 'designo Diamond White Bright'
 'Phantom Black Pearl Effect / Black Roof' 'Nebula Gray Pearl'
 'Deep Crystal Blue Mica' 'Flame Red Clearcoat' 'Lunar Blue Metallic'
 'Bright White Clearcoat' 'Rapid Red Metallic Tinted Clearcoat' 'Caviar'
 'Dark Ash Metallic' 'Velvet Red Pearlcoat' 'Silver Zynith' 'Super Black'
 'Antimatter Blue Metallic' 'Dark Moon Blue Metallic' 'Summit White'
 'Ebony Black' '–' 'Black Cherry' 'Delmonico Red Pearlcoat'
 'Platinum Quartz Metallic' 'Ultra White' 'Python Green'
 'Garnet Red Metallic' 'Snow White Pearl' 'Cajun Red Tintcoat'
 'Midnight Black Metallic' 'Diamond White' 'Mythos Black Metallic'
 'Soul Red Crystal Metallic' 'Atomic Silver' 'Obsidian'
 'Magnetic Metallic' 'Twilight Blue Metallic' 'Star White' 'Stormy Sea'
 'Tango Red Metallic' 'Hyper Red' 'Portofino Gray'
 'MANUFAKTUR Diamond White Bright' 'Snowflake White Pearl'
 'Patriot Blue Pearlcoat' 'Tungsten Metallic' 'Chronos Gray Metallic'
 'Silver Ice Metallic' 'Daytona Gray Pearl Effect'
 'Ruby Red Metallic Tinted Clearcoat' 'Alpine White' 'Eminent White Pearl'
 'Manhattan Noir Metallic' 'Quicksilver Metallic' 'Stellar Black Metallic'
 'Sparkling Silver' 'Blueprint' 'Crystal Black Silica' 'Black Noir Pearl'
 'Arancio Borealis' 'Typhoon Gray' 'Ibis White' 'Graphite Grey'
 'Mineral White' 'Midnight Black' 'Northsky Blue Metallic' 'Alta White'
 'Brilliant Black' 'Jet Black Mica'
 'Daytona Gray Pearl Effect w/ Black Roof' 'Redline Red'
 'Glacier Silver Metallic' 'Magnetic Black' 'Chronos Gray'
 'Red Quartz Tintcoat' 'Nero Noctis' 'Firenze Red Metallic'
 'Iridescent Pearl Tricoat' 'Twilight Black' 'Radiant Red Metallic II'
 'Blue Metallic' 'Glacier White' 'Daytona Gray' 'Rosso Mars Metallic'
 'Wolf Gray' 'Santorin Black' 'Designo Magno Matte'
 'Emerald Green Metallic' 'Ruby Flare Pearl' 'Lunar Silver Metallic'
 'Eiger Grey Metallic' 'Quartzite Grey Metallic' 'Barcelona Red'
 'Beluga Black' 'Matador Red Metallic' 'Billet Silver Metallic Clearcoat'
 'Anodized Blue Metallic' 'Black Forest Green' 'Ice Silver Metallic'
 'Sandstone Metallic' 'Magnetic Gray Clearcoat' 'Crystal Black Pearl'
 'Pacific Blue Metallic' 'Stone Gray Metallic' 'Iconic Silver Metallic'
 'Dark Sapphire' 'Onyx' 'Aventurine Green Metallic' 'China Blue'
 'Majestic Black Pearl' 'Midnight Silver Metallic' 'Sting Gray Clearcoat'
 'Glacier Blue Metallic' 'BLACK' 'Chalk' 'Dark Matter Metallic'
 'Infrared Tintcoat' 'Iridium Metallic' 'Fuji White' 'Alfa White'
 'Kodiak Brown Metallic' 'Aurora Black' 'Onyx Black'
 'Nightfall Gray Metallic' 'Obsidian Black Metallic' 'Phantom Black'
 'Remington Red Metallic' 'designo Diamond White' 'Lizard Green'
 'Rosso Corsa' 'Shadow Gray Metallic' 'Florett Silver' 'Quartz White'
 'DB Black Clearcoat' 'Yulong White' 'Eiger Grey' 'Custom Color'
 'Electric Blue Metallic' 'Tempest' 'Lunar Rock' 'Mosaic Black Metallic'
 'Gecko Pearlcoat' 'White Clearcoat' 'BLU ELEOS'
 'Granite Crystal Metallic Clearcoat' 'Rich Garnet Metallic'
 'Graphite Grey Metallic' 'Bianco Icarus Metallic' 'Satin Steel Metallic'
 'BLUE' 'Moonlight Cloud' 'Matador Red Mica' 'Emin White'
 'Machine Gray Metallic' 'White Platinum Tri-Coat Metallic'
 'Cobra Beige Metallic' 'Cayenne Red Tintcoat' 'Shoreline Blue Pearl'
 'Vik Black' 'Shimmering Silver' 'Bianco Monocerus'
 'Carbonized Gray Metallic' 'Carrara White Metallic' 'Dark Slate Metallic'
 'Dark Graphite Metallic' 'Sonic Silver Metallic'
 'White Knuckle Clearcoat' 'Titanium Silver' 'Anthracite Blue Metallic'
 'Black Obsidian' 'Polymetal Gray Metallic' 'Orca Black Metallic'
 'Wind Chill Pearl' 'Blue Reflex Mica' 'Dark Moss'
 'Selenite Grey Metallic' 'Kemora Gray Metallic' 'Nightfall Mica'
 'Liquid Platinum' 'Mountain Air Metallic' 'Kinetic Blue'
 'Santorini Black' 'Carbon Black Metallic' 'Gentian Blue Metallic'
 'Red Multi' 'Super White' 'Pearl White' 'Typhoon Gray Metallic'
 'Navarra Blue Metallic' 'Bianco Isis' 'Navarra Blue'
 'Volcano Grey Metallic' 'Arctic Gray Metallic' 'Pure White' 'Baltic Gray'
 'Glacier White Metallic' 'Frozen Dark Silver Metallic'
 'Magnetic Gray Metallic' 'Gun Metallic' 'Siren Red Tintcoat'
 'Deep Blue Metallic' 'Cirrus Silver Metallic' 'Deep Black Pearl Effect'
 'Granite' 'Sunset Drift Chromaflair' 'Oryx White Prl'
 'Dark Gray Metallic' 'Bayside Blue' 'Pink' 'Ice' 'Mango Tango Pearlcoat'
 'Burnished Bronze Metallic' 'Verde' 'Arctic White'
 'Portofino Blue Metallic' 'Dazzling White' 'Nero Daytona'
 'Nautical Blue Pearl' 'Imperial Blue Metallic' 'Vulcano Black Metallic'
 'Silver Radiance' 'Hellayella Clearcoat' 'Jungle Green' 'C / C' 'Yulong'
 'Pristine White' 'Silky Silver' 'Caspian Blue' 'Sangria Red'
 'Donington Grey Metallic' 'Apex Blue' 'Rift Metallic' 'Fountain Blue'
 'Balloon White' 'Matte White' 'Frozen White' 'Pacific Blue' 'Rosso'
 'Ironman Silver' 'Octane Red Pearlcoat' 'Selenite Gray Metallic'
 'Hydro Blue Pearlcoat' 'Ingot Silver Metallic' 'Quartz Blue Pearl'
 'Lunare White Metallic' 'Ember Pearlcoat' 'Brands Hatch Gray Metallic'
 'Navarre Blue' 'Midnight Blue Metallic' 'Shadow Black' 'Go Mango!'
 'Maximum Steel Metallic' 'Silver Flare Metallic'
 'Billet Clearcoat Metallic' 'Hampton Gray' 'Red Obsession' 'Silver Mist'
 'Scarlet Ember' 'Crimson Red Tintcoat' 'Tan' 'Isle of Man Green Metallic'
 'Crystal Black' 'Glacier' 'Iridium Silver Metallic'
 'Bronze Dune Metallic' 'Maroon' 'Platinum Gray Metallic' 'Passion Red'
 'Silician Yellow' 'Volcanic Orange' 'Crystal White Pearl' 'Reflex Silver'
 'Blue Caelum' 'Thunder Gray' 'Ultra Black' 'Indus Silver' 'Horizon Blue'
 'Grigio Nimbus' 'Carpathian Grey' 'Ametrin Metallic' 'Jupiter Red'
 'GT SILVER']
-----------------------------------------
int_col
156
['Gray' 'Beige' 'Black' '–' 'Blue' 'White' 'Red' 'Brown' 'Dark Galvanized'
 'Parchment.' 'Boulder' 'Orange' 'Medium Earth Gray' 'Ebony'
 'Canberra Beige' 'Jet Black' 'Silver' 'Light Platinum / Jet Black'
 'Macchiato/Magmagrey' 'Gold' 'Cloud' 'Rioja Red' 'Global Black' 'Green'
 'Medium Stone' 'Navy Pier' 'Dark Ash' 'BLACK' 'Portland' 'Sandstone'
 'Canberra Beige/Black' 'Diesel Gray / Black' 'Sarder Brown' 'Black Onyx'
 'White / Brown' 'Black/Gun Metal' 'Slate' 'Satin Black'
 'Macchiato Beige/Black' 'Charcoal' 'Black / Express Red' 'Cappuccino'
 'Aragon Brown' 'Parchment' 'Oyster W/Contrast' 'Adrenaline Red' 'Ebony.'
 'Shara Beige' 'Graystone' 'Pearl Beige' 'Nero Ade' 'Graphite'
 'Tan/Ebony/Ebony' 'Charcoal Black' 'Medium Ash Gray' 'Ebony Black'
 'Light Titanium' 'Sakhir Orange' 'Tan' 'Rock Gray' 'Brandy'
 'Carbon Black' 'Amber' 'Black w/Red Stitching' 'Hotspur' 'Chateau' 'Ice'
 'Deep Garnet' 'Blk' 'Grace White' 'Oyster/Black' 'Mesa' 'Espresso'
 'Black/Graphite' 'Ebony / Ebony Accents' 'Tan/Ebony' 'Ceramic'
 'Medium Dark Slate' 'Graphite w/Gun Metal' 'Obsidian Black'
 'Cocoa / Dune' 'Roast' 'Yellow' 'Hotspur Hide' 'Gray w/Blue Bolsters'
 'Chestnut' 'Saiga Beige' 'ORANGE' 'Charles Blue' 'Walnut' 'Ivory / Ebony'
 'Caramel' 'Pimento Red w/Ebony' 'Saddle Brown' 'Dark Gray'
 'Silk Beige/Espresso Brown' 'Black / Brown' 'Ebony/Light Oyster Stitch'
 'Ebony / Pimento' 'Mistral Gray / Raven' 'Giallo Taurus / Nero Ade'
 'Tension' 'Medium Pewter' 'Black / Saddle' 'Camel Leather'
 'Black/Saddle Brown' 'Macchiato' 'Anthracite' 'Mocha' 'Whisper Beige'
 'Titan Black / Quarzit' 'Sahara Tan' 'Porpoise' 'Black/Red' 'Titan Black'
 'AMG Black' 'Deep Cypress' 'Light Slate' 'Red / Black' 'Beluga Hide'
 'Tupelo' 'Gideon' 'Rhapsody Blue' 'Medium Light Camel' 'Almond Beige'
 'Black / Gray' 'Nero' 'Agave Green' 'Deep Chestnut' 'Dark Auburn' 'Shale'
 'Silk Beige/Black' 'BEIGE' 'Magma Red' 'Linen' 'Black / Stone Grey'
 'Sand Beige' 'Red/Black' 'Bianco Polar' 'Light Gray' 'Platinum' 'Sport'
 'Ash' 'Black / Graphite' 'Nougat Brown' 'Camel' 'Mountain Brown'
 'Pimento / Ebony' 'Classic Red' 'Sakhir Orange/Black' 'Cobalt Blue'
 'Very Light Cashmere' 'Kyalami Orange' 'Orchid' 'Beluga' 'WHITE']
-----------------------------------------
accident
2
['None reported' 'At least 1 accident or damage reported' nan]
-----------------------------------------
clean_title
1
['Yes' nan]
-----------------------------------------

In [ ]:
for col in df_train.select_dtypes(include='object'):
    print(df_train[col].value_counts().sort_values(ascending=False).head(10))
    print('----------------------------------------------------')

brand
Ford             23088
Mercedes-Benz    19172
BMW              17028
Chevrolet        16335
Audi             10887
Porsche          10612
Land              9525
Toyota            8850
Lexus             8643
Jeep              6474
Name: count, dtype: int64
----------------------------------------------------
model
F-150 XLT               2945
M3 Base                 2229
Camaro 2SS              1709
M4 Base                 1622
Mustang GT Premium      1526
F-150 Lariat            1410
E-Class E 350 4MATIC    1357
1500 Laramie            1249
911 Carrera S           1219
Corvette Base           1184
Name: count, dtype: int64
----------------------------------------------------
fuel_type
Gasoline          165940
Hybrid              6832
E85 Flex Fuel       5406
Diesel              3955
–                    781
Plug-In Hybrid       521
not supported         15
Name: count, dtype: int64
----------------------------------------------------
engine
355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel             3462
240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel             2902
420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel             2841
2.0L I4 16V GDI DOHC Turbo                               2680
375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel            2451
340.0HP 3.0L V6 Cylinder Engine Gasoline Fuel            2436
490.0HP 6.2L 8 Cylinder Engine Gasoline Fuel             2187
455.0HP 6.2L 8 Cylinder Engine Gasoline Fuel             2138
425.0HP 3.0L Straight 6 Cylinder Engine Gasoline Fuel    2134
300.0HP 3.0L Straight 6 Cylinder Engine Gasoline Fuel    2084
Name: count, dtype: int64
----------------------------------------------------
transmission
A/T                               49904
8-Speed A/T                       20645
Transmission w/Dual Shift Mode    19255
6-Speed A/T                       18044
6-Speed M/T                       11998
7-Speed A/T                       11124
Automatic                         10691
8-Speed Automatic                  8431
10-Speed A/T                       8044
9-Speed A/T                        3866
Name: count, dtype: int64
----------------------------------------------------
ext_col
Black     48658
White     43815
Gray      25293
Silver    16995
Blue      14555
Red        9901
Green      2698
Gold       1668
Brown      1162
Orange     1139
Name: count, dtype: int64
----------------------------------------------------
int_col
Black        107674
Beige         24495
Gray          21204
Brown          5810
Red            5145
White          4743
–              4527
Jet Black      2398
Ebony          1833
Orange          932
Name: count, dtype: int64
----------------------------------------------------
accident
None reported                             144514
At least 1 accident or damage reported     41567
Name: count, dtype: int64
----------------------------------------------------
clean_title
Yes    167114
Name: count, dtype: int64
----------------------------------------------------

In [ ]:
df_train.isna().sum()

id                  0
brand               0
model               0
model_year          0
milage              0
fuel_type        5083
engine              0
transmission        0
ext_col             0
int_col             0
accident         2452
clean_title     21419
price               0
dtype: int64

In [ ]:
df_train.isna().sum()

id                  0
brand               0
model               0
model_year          0
milage              0
fuel_type        5083
engine              0
transmission        0
ext_col             0
int_col             0
accident         2452
clean_title     21419
price               0
dtype: int64

In [ ]:
df_train.drop('id',axis=1,inplace=True)
df_test.drop('id',axis=1,inplace=True)

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   brand         188533 non-null  object
 1   model         188533 non-null  object
 2   model_year    188533 non-null  int64
 3   milage        188533 non-null  int64
 4   fuel_type     183450 non-null  object
 5   engine        188533 non-null  object
 6   transmission  188533 non-null  object
 7   ext_col       188533 non-null  object
 8   int_col       188533 non-null  object
 9   accident      186081 non-null  object
 10  clean_title   167114 non-null  object
 11  price         188533 non-null  int64
dtypes: int64(3), object(9)
memory usage: 17.3+ MB

# **VIS**

In [ ]:
cols_dict = {
      'brand':'brand',
      'model_year':'model_year',
      "accident": "accident",
      "exterior color" : "ext_col",
      "interior color" : "int_col",
}
target='price'

In [ ]:
props1 = "background-color: white; color: maroon; font-weight: bold; "
props2 = "background-color: white; color: blue; font-weight: bold; "

In [ ]:
for label, col in cols_dict.items():
  t=tr[[col,target]].groupby(col).agg({target: ["max", "min", "mean", "median", "size"]})
  display(t.sort_values(by = col, ascending = True).\
                transpose().\
                style.format(formatter = '{:,.0f}').\
                set_caption(f"\nPrice details by {label}\n").\
                highlight_max(axis=1, props = props1).\
                highlight_min(axis=1, props = props2)
                 )
  print("\n\n\n")

In [ ]:
pd.options.display.float_format = '{:.1f}'.format

In [ ]:
import re

# **Feature Extraction**

In [ ]:
df_train['Horse_power']= df_train['engine'].str.extract(r'(\d+)\.?\d*HP').astype(float)
df_train['Engine_Displacement']= df_train['engine'].str.extract(r'(\d+\.?\d*)L').astype(float)
df_train['Cylinder_Count']= df_train['engine'].str.extract(r'(\d+) Cylinder ').astype(float)

df_test['Horse_power']= df_test['engine'].str.extract(r'(\d+)\.?\d*HP').astype(float)
df_test['Engine_Displacement']= df_test['engine'].str.extract(r'(\d+\.?\d*)L').astype(float)
df_test['Cylinder_Count']= df_test['engine'].str.extract(r'(\d+) Cylinder ').astype(float)

cylinder_config={'V','Flat','Straight'}
Turbocharger = {'Turbo','Twin Turbo'}
engine_type ={'Gasoline','Electric','Hybrid'}
FUEL_SYSTEMS = {'MPFI', 'GDI', 'PDI', 'TFSI','DOHC', 'SOHC'}

In [ ]:
def zoo(word,cylinder_config):
  for i in cylinder_config:
    if i in word:
      return i
  return 'Nan'

In [ ]:
df_train['cylinder_config']=df_train['engine'].apply(zoo,args=(cylinder_config,))
df_train['Turbocharger']=df_train['engine'].apply(zoo,args=(Turbocharger,))
df_train['engine_type']=df_train['engine'].apply(zoo,args=(engine_type,))
df_train['FUEL_SYSTEMS']=df_train['engine'].apply(zoo,args=(FUEL_SYSTEMS,))

df_test['cylinder_config']=df_test['engine'].apply(zoo,args=(cylinder_config,))
df_test['Turbocharger']=df_test['engine'].apply(zoo,args=(Turbocharger,))
df_test['engine_type']=df_test['engine'].apply(zoo,args=(engine_type,))
df_test['FUEL_SYSTEMS']=df_test['engine'].apply(zoo,args=(FUEL_SYSTEMS,))

In [ ]:
df_train

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Horse_power,Engine_Displacement,Cylinder_Count,cylinder_config,Turbocharger,engine_type,FUEL_SYSTEMS
0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200,172.0,1.6,4.0,Nan,Nan,Gasoline,Nan
1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999,252.0,3.9,8.0,Nan,Nan,Gasoline,Nan
2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900,320.0,5.3,8.0,Nan,Nan,Nan,Nan
3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000,420.0,5.0,8.0,Nan,Nan,Gasoline,Nan
4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500,208.0,2.0,4.0,Nan,Nan,Gasoline,Nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Beige,None reported,Yes,27500,420.0,6.2,8.0,Nan,Nan,Gasoline,Nan
188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,At least 1 accident or damage reported,Yes,30000,385.0,3.0,6.0,V,Nan,Gasoline,Nan
188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Black,None reported,Yes,86900,469.0,4.0,8.0,Nan,Nan,Gasoline,Nan
188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,3.0L,1-Speed Automatic,Daytona Gray Pearl Effect,Black,None reported,NaN,84900,NaN,3.0,NaN,Nan,Nan,Nan,Nan
188532,Porsche,Macan Base,2016,59500,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,Black,None reported,Yes,28995,252.0,2.0,4.0,Nan,Nan,Gasoline,Nan

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   brand                188533 non-null  object
 1   model                188533 non-null  object
 2   model_year           188533 non-null  int64
 3   milage               188533 non-null  int64
 4   fuel_type            183450 non-null  object
 5   engine               188533 non-null  object
 6   transmission         188533 non-null  object
 7   ext_col              188533 non-null  object
 8   int_col              188533 non-null  object
 9   accident             186081 non-null  object
 10  clean_title          167114 non-null  object
 11  price                188533 non-null  int64
 12  Horse_power          155274 non-null  float64
 13  Engine_Displacement  174319 non-null  float64
 14  Cylinder_Count       150625 non-null  float64
 15  cylinder_config      188533 non-null  object
 16  Turbocharger         188533 non-null  object
 17  engine_type          188533 non-null  object
 18  FUEL_SYSTEMS         188533 non-null  object
dtypes: float64(3), int64(3), object(13)
memory usage: 27.3+ MB

In [ ]:
df_train['transmission'].unique()

array(['A/T', 'Transmission w/Dual Shift Mode', '7-Speed A/T',
       '8-Speed A/T', '10-Speed Automatic', '1-Speed A/T', '6-Speed A/T',
       '10-Speed A/T', '9-Speed A/T', '8-Speed Automatic',
       '9-Speed Automatic', '5-Speed A/T', 'Automatic',
       '7-Speed Automatic with Auto-Shift', 'CVT Transmission',
       '5-Speed M/T', 'M/T', '6-Speed M/T', '6-Speed Automatic',
       '4-Speed Automatic', '7-Speed M/T', '2-Speed A/T',
       '1-Speed Automatic', 'Automatic CVT', '4-Speed A/T',
       '6-Speed Manual', 'Transmission Overdrive Switch',
       '8-Speed Automatic with Auto-Shift', '7-Speed Manual',
       '7-Speed Automatic', '9-Speed Automatic with Auto-Shift',
       '6-Speed Automatic with Auto-Shift',
       '6-Speed Electronically Controlled Automatic with O', 'F', 'CVT-F',
       '8-Speed Manual', 'Manual', '–', '2', '6 Speed At/Mt',
       '5-Speed Automatic', '2-Speed Automatic', '8-SPEED A/T', '7-Speed',
       'Variable', 'Single-Speed Fixed Gear', '8-SPEED AT',
       '10-Speed Automatic with Overdrive', '7-Speed DCT Automatic',
       'SCHEDULED FOR OR IN PRODUCTION', '6-Speed', '6 Speed Mt'],
      dtype=object)

In [ ]:
print(df_train['transmission'].iloc[:150].to_string())

0                                    A/T
1                                    A/T
2                                    A/T
3         Transmission w/Dual Shift Mode
4                            7-Speed A/T
5                                    A/T
6                            8-Speed A/T
7                                    A/T
8                     10-Speed Automatic
9         Transmission w/Dual Shift Mode
10                                   A/T
11                           1-Speed A/T
12                           6-Speed A/T
13                                   A/T
14                                   A/T
15                           7-Speed A/T
16                          10-Speed A/T
17                           8-Speed A/T
18                           7-Speed A/T
19                           9-Speed A/T
20                     8-Speed Automatic
21                           8-Speed A/T
22                           6-Speed A/T
23        Transmission w/Dual Shift Mode
24                           6-Speed A/T
25                           6-Speed A/T
26                           6-Speed A/T
27                           8-Speed A/T
28                                   A/T
29        Transmission w/Dual Shift Mode
30        Transmission w/Dual Shift Mode
31                           9-Speed A/T
32                                   A/T
33                           7-Speed A/T
34                           8-Speed A/T
35                                   A/T
36                                   A/T
37                                   A/T
38                           7-Speed A/T
39                     9-Speed Automatic
40                           5-Speed A/T
41                                   A/T
42                           8-Speed A/T
43                     8-Speed Automatic
44                           8-Speed A/T
45                     8-Speed Automatic
46                                   A/T
47                           7-Speed A/T
48                                   A/T
49                           8-Speed A/T
50        Transmission w/Dual Shift Mode
51                             Automatic
52                           1-Speed A/T
53        Transmission w/Dual Shift Mode
54                           7-Speed A/T
55                                   A/T
56                                   A/T
57                                   A/T
58                                   A/T
59                                   A/T
60                     9-Speed Automatic
61                                   A/T
62                           8-Speed A/T
63                           6-Speed A/T
64                           7-Speed A/T
65                           8-Speed A/T
66                                   A/T
67                                   A/T
68                                   A/T
69                           7-Speed A/T
70     7-Speed Automatic with Auto-Shift
71                           8-Speed A/T
72                             Automatic
73                                   A/T
74                      CVT Transmission
75        Transmission w/Dual Shift Mode
76                                   A/T
77                                   A/T
78                           5-Speed A/T
79                           7-Speed A/T
80                           8-Speed A/T
81                           5-Speed M/T
82                                   A/T
83                                   A/T
84                    10-Speed Automatic
85                          10-Speed A/T
86                           7-Speed A/T
87                           6-Speed A/T
88                                   M/T
89                           6-Speed M/T
90                           6-Speed A/T
91                     6-Speed Automatic
92                           5-Speed A/T
93                                   A/T
94                           8-Speed A/T
95                                   A/T
96                                   A/T
97                          10-Speed A/T
98                                   M/T
99                           6-Speed A/T
100       Transmission w/Dual Shift Mode
101                          7-Speed A/T
102                          6-Speed A/T
103                          7-Speed A/T
104                          6-Speed M/T
105                          7-Speed A/T
106       Transmission w/Dual Shift Mode
107                                  A/T
108       Transmission w/Dual Shift Mode
109                          8-Speed A/T
110                          8-Speed A/T
111                    6-Speed Automatic
112                          6-Speed A/T
113                                  A/T
114                                  A/T
115                                  A/T
116                          8-Speed A/T
117                                  A/T
118       Transmission w/Dual Shift Mode
119                          6-Speed A/T
120                                  A/T
121                          6-Speed A/T
122                            Automatic
123                    8-Speed Automatic
124       Transmission w/Dual Shift Mode
125                                  A/T
126                    8-Speed Automatic
127                                  A/T
128                                  A/T
129                          7-Speed A/T
130                                  A/T
131                                  A/T
132                                  A/T
133                    4-Speed Automatic
134                    8-Speed Automatic
135                                  A/T
136                                  A/T
137                                  A/T
138       Transmission w/Dual Shift Mode
139                          8-Speed A/T
140                          6-Speed A/T
141                                  A/T
142       Transmission w/Dual Shift Mode
143                         10-Speed A/T
144                    8-Speed Automatic
145                    8-Speed Automatic
146                          7-Speed M/T
147                    9-Speed Automatic
148                          6-Speed A/T
149       Transmission w/Dual Shift Mode

In [ ]:
df_train['transmission'].value_counts()

transmission
A/T                                                   49904
8-Speed A/T                                           20645
Transmission w/Dual Shift Mode                        19255
6-Speed A/T                                           18044
6-Speed M/T                                           11998
7-Speed A/T                                           11124
Automatic                                             10691
8-Speed Automatic                                      8431
10-Speed A/T                                           8044
9-Speed A/T                                            3866
5-Speed A/T                                            3217
10-Speed Automatic                                     3164
6-Speed Automatic                                      2799
4-Speed A/T                                            2546
5-Speed M/T                                            2409
9-Speed Automatic                                      2325
CVT Transmission                                       1990
1-Speed A/T                                            1869
M/T                                                    1179
7-Speed Automatic with Auto-Shift                      1172
Automatic CVT                                           829
8-Speed Automatic with Auto-Shift                       549
1-Speed Automatic                                       365
7-Speed M/T                                             355
6-Speed Manual                                          211
7-Speed Automatic                                       178
5-Speed Automatic                                       159
Transmission Overdrive Switch                           156
7-Speed Manual                                          151
6-Speed Automatic with Auto-Shift                       111
2                                                        91
–                                                        87
2-Speed A/T                                              71
Variable                                                 66
F                                                        65
4-Speed Automatic                                        48
10-Speed Automatic with Overdrive                        40
6 Speed Mt                                               37
9-Speed Automatic with Auto-Shift                        33
6-Speed Electronically Controlled Automatic with O       31
7-Speed                                                  29
8-Speed Manual                                           28
Manual                                                   27
6-Speed                                                  27
2-Speed Automatic                                        22
6 Speed At/Mt                                            20
7-Speed DCT Automatic                                    18
Single-Speed Fixed Gear                                  16
CVT-F                                                    15
8-SPEED AT                                               13
8-SPEED A/T                                               7
SCHEDULED FOR OR IN PRODUCTION                            6
Name: count, dtype: int64

In [ ]:
def extract_transmition (word):
  def get_number ():
    n=re.findall('\d+',word)
    return n[0] if n else ''
  if any(i in word for i in ['AT','A/T','At/Mt','Automatic'] ):
    return ('AT'+str(get_number()))
  elif any(i in word for i in ['CVT'] ):
     return ('CVT'+str(get_number()))
  elif any(i in word for i in ['Manual','M/T'] ):
    return ('MT'+str(get_number()))
  else :
    return 'other'

In [ ]:
df_train['new_transmission']=df_train['transmission'].apply(extract_transmition)
df_test['new_transmission']=df_test['transmission'].apply(extract_transmition)

In [ ]:
df_train[['new_transmission','transmission']].head(20)

   new_transmission                    transmission
0                AT                             A/T
1                AT                             A/T
2                AT                             A/T
3             other  Transmission w/Dual Shift Mode
4               AT7                     7-Speed A/T
5                AT                             A/T
6               AT8                     8-Speed A/T
7                AT                             A/T
8              AT10              10-Speed Automatic
9             other  Transmission w/Dual Shift Mode
10               AT                             A/T
11              AT1                     1-Speed A/T
12              AT6                     6-Speed A/T
13               AT                             A/T
14               AT                             A/T
15              AT7                     7-Speed A/T
16             AT10                    10-Speed A/T
17              AT8                     8-Speed A/T
18              AT7                     7-Speed A/T
19              AT9                     9-Speed A/T

In [ ]:
df_train.drop(['engine','transmission','model_year','model'],axis=1,inplace=True)
df_test.drop(['engine','transmission','model_year','model'],axis=1,inplace=True)

In [ ]:
df_train.head()

,brand,milage,fuel_type,ext_col,int_col,accident,clean_title,price,Horse_power,Engine_Displacement,Cylinder_Count,cylinder_config,Turbocharger,engine_type,FUEL_SYSTEMS,new_transmission
0,MINI,213000,Gasoline,Yellow,Gray,None reported,Yes,4200,172.0,1.6,4.0,Nan,Nan,Gasoline,Nan,AT
1,Lincoln,143250,Gasoline,Silver,Beige,At least 1 accident or damage reported,Yes,4999,252.0,3.9,8.0,Nan,Nan,Gasoline,Nan,AT
2,Chevrolet,136731,E85 Flex Fuel,Blue,Gray,None reported,Yes,13900,320.0,5.3,8.0,Nan,Nan,Nan,Nan,AT
3,Genesis,19500,Gasoline,Black,Black,None reported,Yes,45000,420.0,5.0,8.0,Nan,Nan,Gasoline,Nan,other
4,Mercedes-Benz,7388,Gasoline,Black,Beige,None reported,Yes,97500,208.0,2.0,4.0,Nan,Nan,Gasoline,Nan,AT7

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 16 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   brand                188533 non-null  object
 1   milage               188533 non-null  int64
 2   fuel_type            183450 non-null  object
 3   ext_col              188533 non-null  object
 4   int_col              188533 non-null  object
 5   accident             186081 non-null  object
 6   clean_title          167114 non-null  object
 7   price                188533 non-null  int64
 8   Horse_power          155274 non-null  float64
 9   Engine_Displacement  174319 non-null  float64
 10  Cylinder_Count       150625 non-null  float64
 11  cylinder_config      188533 non-null  object
 12  Turbocharger         188533 non-null  object
 13  engine_type          188533 non-null  object
 14  FUEL_SYSTEMS         188533 non-null  object
 15  new_transmission     188533 non-null  object
dtypes: float64(3), int64(2), object(11)
memory usage: 23.0+ MB

In [ ]:
df_train.isna().sum()

brand                      0
milage                     0
fuel_type               5083
ext_col                    0
int_col                    0
accident                2452
clean_title            21419
price                      0
Horse_power            33259
Engine_Displacement    14214
Cylinder_Count         37908
cylinder_config            0
Turbocharger               0
engine_type                0
FUEL_SYSTEMS               0
new_transmission           0
dtype: int64

In [ ]:
y=df_train['price']
df_train=df_train.drop('price',axis=1)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df_train,y,test_size=.3,random_state=42)

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   brand                188533 non-null  object
 1   milage               188533 non-null  int64
 2   fuel_type            183450 non-null  object
 3   ext_col              188533 non-null  object
 4   int_col              188533 non-null  object
 5   accident             186081 non-null  object
 6   clean_title          167114 non-null  object
 7   Horse_power          155274 non-null  float64
 8   Engine_Displacement  174319 non-null  float64
 9   Cylinder_Count       150625 non-null  float64
 10  cylinder_config      188533 non-null  object
 11  Turbocharger         188533 non-null  object
 12  engine_type          188533 non-null  object
 13  FUEL_SYSTEMS         188533 non-null  object
 14  new_transmission     188533 non-null  object
dtypes: float64(3), int64(1), object(11)
memory usage: 21.6+ MB

# **PipeLine**

In [ ]:
num_col = df_train.select_dtypes(include='number').columns
cat_col = df_train.select_dtypes(include='object').columns

In [ ]:
# # num_pipe=Pipeline(steps=[
#       # ('imputer',SimpleImputer(strategy='mean')),
#       # ('scaler',StandardScaler() )  ])
# cat_pipe=Pipeline(steps=[
#       ('imputer',SimpleImputer(strategy='most_frequent')),
#       ('encoder',OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1))
#                  ] )

In [ ]:
# df_transformer=ColumnTransformer(
#             transformers=[
#                   # ('num', num_pipe, num_col),
#                   ('cat', cat_pipe, cat_col)
#                  ] )

In [ ]:
# final_pipe= Pipeline(steps=[
#     ('prepcorcessor',df_transformer)
# ])

In [ ]:
# x_train_done = final_pipe.fit_transform(x_train)
# x_test_done = final_pipe.transform(x_test)

In [ ]:
num_imputer= SimpleImputer(strategy='mean')
cat_imputer= SimpleImputer(strategy='most_frequent')
encoder = OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)
scaler = StandardScaler()
for col in num_col:
  x_train[col] = num_imputer.fit_transform(x_train[[col]])
  x_test[col] = num_imputer.transform(x_test[[col]])

  df_test[col] = num_imputer.transform(df_test[[col]])

  x_train[col] = scaler.fit_transform(x_train[[col]])
  x_test[col] = scaler.transform(x_test[[col]])
  df_test[col] = scaler.transform(df_test[[col]])
for col in cat_col:
  x_train[[col]] = cat_imputer.fit_transform(x_train[col].values.reshape(-1,1))
  x_test[[col]] = cat_imputer.transform(x_test[col].values.reshape(-1,1))

  df_test[[col]] = cat_imputer.transform(df_test[col].values.reshape(-1,1))

  x_train[col] = encoder.fit_transform(x_train[[col]])
  x_test[col] = encoder.transform(x_test[[col]])

  df_test[col] = encoder.transform(df_test[[col]])

In [ ]:
df_train.head()

,brand,milage,fuel_type,ext_col,int_col,accident,clean_title,Horse_power,Engine_Displacement,Cylinder_Count,cylinder_config,Turbocharger,engine_type,FUEL_SYSTEMS,new_transmission
0,MINI,213000,Gasoline,Yellow,Gray,None reported,Yes,172.0,1.6,4.0,Nan,Nan,Gasoline,Nan,AT
1,Lincoln,143250,Gasoline,Silver,Beige,At least 1 accident or damage reported,Yes,252.0,3.9,8.0,Nan,Nan,Gasoline,Nan,AT
2,Chevrolet,136731,E85 Flex Fuel,Blue,Gray,None reported,Yes,320.0,5.3,8.0,Nan,Nan,Nan,Nan,AT
3,Genesis,19500,Gasoline,Black,Black,None reported,Yes,420.0,5.0,8.0,Nan,Nan,Gasoline,Nan,other
4,Mercedes-Benz,7388,Gasoline,Black,Beige,None reported,Yes,208.0,2.0,4.0,Nan,Nan,Gasoline,Nan,AT7

In [ ]:
df_train['clean_title']

0         Yes
1         Yes
2         Yes
3         Yes
4         Yes
         ...
188528    Yes
188529    Yes
188530    Yes
188531    NaN
188532    Yes
Name: clean_title, Length: 188533, dtype: object

In [ ]:
zob=pd.DataFrame(x_train,columns=df_train.columns)
zob

,brand,milage,fuel_type,ext_col,int_col,accident,clean_title,Horse_power,Engine_Displacement,Cylinder_Count,cylinder_config,Turbocharger,engine_type,FUEL_SYSTEMS,new_transmission
69007,53.0,1.1,2.0,304.0,14.0,0.0,0.0,-0.9,0.1,-0.3,3.0,0.0,1.0,3.0,0.0
68561,27.0,-0.1,2.0,263.0,122.0,1.0,0.0,0.0,0.6,0.0,3.0,0.0,3.0,0.0,6.0
22502,3.0,-0.7,2.0,263.0,14.0,1.0,0.0,-0.3,-0.6,-0.3,3.0,0.0,1.0,3.0,0.0
4493,10.0,1.4,1.0,263.0,71.0,0.0,0.0,-0.5,-0.2,-0.3,3.0,0.0,3.0,3.0,0.0
32131,31.0,0.1,2.0,304.0,14.0,1.0,0.0,-1.6,-1.7,-1.7,1.0,0.0,1.0,3.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119879,9.0,0.5,2.0,234.0,10.0,0.0,0.0,0.1,1.5,1.2,1.0,0.0,1.0,3.0,13.0
103694,4.0,-0.2,2.0,29.0,14.0,1.0,0.0,-0.2,-0.6,-0.3,2.0,0.0,1.0,3.0,7.0
131932,43.0,-0.7,2.0,29.0,14.0,1.0,0.0,0.7,-0.6,-0.3,0.0,0.0,1.0,3.0,8.0
146867,36.0,2.4,2.0,29.0,14.0,1.0,0.0,-0.7,-0.2,-0.3,3.0,0.0,1.0,3.0,7.0
121958,32.0,-1.2,2.0,177.0,14.0,1.0,0.0,0.0,-0.6,0.0,3.0,1.0,3.0,0.0,8.0

In [ ]:
import xgboost as xgb
from lightgbm import LGBMRegressor

/usr/local/lib/python3.10/dist-packages/dask/dataframe/__init__.py:42: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

In [ ]:
xgb=xgb.XGBRegressor(tree_method ="hist",
                          device               = "cuda" ,
                          objective             = "reg:squarederror",
                          eval_metric           = "rmse",
                          random_state          = 42,
                          colsample_bytree      = 0.45,
                          learning_rate       = 0.025,
                          max_depth          = 7,
                          n_estimators          = 3000,
                          reg_alpha          = 0.001,
                        reg_lambda            = 0.001,
                          min_child_weight      = 18,
                          verbosity = 0,
                          enable_categorical    = True,
)
lgb_params= {
        'n_epochs': 1000,
        'learning_rate': 0.01,
        'colsample_bytree': 0.55,
        'bagging_fraction': 0.8,
        'num_leaves': 3072,
        'min_child_samples': 12,
        'reg_lambda': 64, # not 128
        'max_bin': 255,
        'max_depth': 10,
        'reg_alpha': 0,
        'verbose': -1,
    }

In [ ]:
lgb_reg = LGBMRegressor(**lgb_params,loss_function='RMSE',verbosity=-1)
lgb_reg.fit(x_train,y_train)
xgb.fit(x_train,y_train)
y_pred1=xgb.predict(x_test)
y_pred= lgb_reg.predict(x_test)
print(np.sqrt(mean_squared_error(y_test,y_pred) ))
np.sqrt(mean_squared_error(y_test,y_pred1) )

67693.88342546465

67465.69589013768

In [ ]:
print(r2_score(y_test,y_pred))
r2_score(y_test,y_pred1)

0.13224482499687962

0.13808515117555675

In [ ]:
y_zz.drop('id',axis=1,inplace=True)

In [ ]:
y_p1= xgb.predict(df_test)
y_p2 = lgb_reg.predict(df_test)
# print(np.sqrt(mean_squared_error(y_zz,y_p1) ))
# print(np.sqrt(mean_squared_error(y_zz,y_p2) ))

34359.48707579107
16082.830611508922

In [ ]:
submission = pd.DataFrame({
    'id':ts['id'],
    'price':y_p2

})

In [ ]:
submission.head()

       id   price
0  188533 27054.6
1  188534 65426.3
2  188535 50032.1
3  188536 42602.6
4  188537 34316.2

In [ ]:
submission.to_csv('submission.csv', index=False)